#!/bin/bash
main () {
	if [ $# == 0 ] ; then
		find_default_interface
		traceroutes $default_route #trace routes through default ni
	else
		for interface in $@; do #iterate through newtork interfaces
			traceroutes $interface #traceroutes for each network interface
		done
	fi
}

traceroutes () {
	echo "Scaning local network via $1 interface...."
	ip_array=$( arp-scan --interface=$1 --localnet | awk '{ print $1 }' ) #Generate an array of ip addresses on local network

	I=("${ip_array[@]:20:-11}") #Remove unwanted terms from ip_array
	ip_array="${I[@]}"

	for ip in $ip_array; do	#Trace routes of all ip addr
		echo $( traceroute --max-hops=1 $ip ) #Only one hop seems to be necessary but more hops may resolve more names
	done
}

find_default_interface () {
	default_route=''
	echo "Detecting active network interfaces...."
	active_interfaces=$( route | awk '{ print $8 }' ) #Generate an array of active interfaces

	echo $active_interfaces
	for interface in $active_interfaces; do
        	if [ $interface == wlan0 ] ; then
                	default_route='wlan0'
        	else
                	if [ $interface == eth0 ] ; then
                        	default_route='eth0'
                	fi
        	fi
	done
	echo "Default $default_route"
}

main $@ #call the main funtion
